### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by Zap-English** [depuits/PlaylistExtractor#1]
I tried your playlist extractor. It doesn't read UTF-8 encoded files. It trashes the file names and tags. Cna you fix this?

**Comment by depuits** [comment]
Do you have an example file which I could use for testing? The files I create don't seem to be affected by the encoding. There is probably a weird character in your file where the Unicode goes wrong.

**Comment by Zap-English** [comment]
send me your email and i'll send it to you

**Comment by depuits** [comment]
You can add a gzip file right here.
Example: [test.m3u.gz](https://github.com/depuits/PlaylistExtractor/files/969682/test.m3u.gz)

More info can be found [here](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/).

**Comment by Zap-English** [comment]
you could also give me your email. This site says it will accept zip files, but it doesn't
and i'm not going to install more software just so i can send you one file

**Comment by depuits** [comment]
I had the same problem but it does accept the **gz** extension. You can just rename the `.zip` to `.gz` if you can't actually make a gz file. If that doesn't work you can sent it to **colmanjoeri@msn.com**.

**Comment by depuits** [comment]
UTF8 encoding is now supported in the latest version.
